### ISSUE TITLE
keep units in sync with encoding attribute

### ISSUE THREAD

**Issue by raybellwaves** [xarray-contrib/pint-xarray#111] opened 2021-06-02 15:49 UTC
I learnt in https://github.com/xarray-contrib/pint-xarray/issues/109 you have a units attribute on a DataArray and you can also have ~~units~~ a scale and an offset in an encoding attribute. Sorry this isn't easily reproducible. I think netcdf files obtained from the Climate Data Store have units in the encoding attribute. I think the pint-xarray operations do not interact with that leading to strange round trip behavior (reading and writing).

**Comment by keewis** [comment] 2021-06-02 22:04
that's strange, I didn't think `xarray` interacts with the `"units"` attribute except from datetime variables. Can you post the values of `.attrs` and `.encoding` before `quantify`ing, immediately before saving to netcdf and after loading again? Even better would be a small file I can play with, but in any case I can't really do much unless I can understand the issue.

**Comment by raybellwaves** [comment] 2021-06-03 03:07
[reanalysis-era5-land_0.25_t2m_CO_2020_01.nc.zip](https://github.com/xarray-contrib/pint-xarray/files/6588631/reanalysis-era5-land_0.25_t2m_CO_2020_01.nc.zip)

Here's a file. It's ERA5-land.

```
import xarray as xr

ds = xr.open_dataset("reanalysis-era5-land_0.25_t2m_CO_2020_01.nc")

>>> ds["t2m"].encoding
{'source': '/Users/ray/Downloads/reanalysis-era5-land_0.25_t2m_CO_2020_01.nc', 'original_shape': (744, 21, 21), 'dtype': dtype('int16'), 'missing_value': -32767, '_FillValue': -32767, 'scale_factor': 0.0006500423894110363, 'add_offset': 267.39366454179356}
```

I think it's the 'add_offset' that keeps the dataset "kelvin" like even after converting units.

**Comment by keewis** [comment] 2021-06-04 21:58
thanks, I can reproduce. Apparently, it's not just `add_offset` but also `scale_factor` and `dtype=dtype("int16")` (which then requires `_FillValue` because the data is in `float`):
```python
In [54]: arr = xr.DataArray([270, 280, 290], dims="x", attrs={"units": "K"}, name="arr")
    ...: arr.encoding = {
    ...:     "add_offset": 267.39366454179356,
    ...:     "scale_factor": 0.0006500423894110363,
    ...:     "dtype": np.dtype("int16"),
    ...:     "_FillValue": -32767,
    ...: }
    ...: arr
Out[54]: 
<xarray.DataArray 'arr' (x: 3)>
array([270, 280, 290])
Dimensions without coordinates: x
Attributes:
    units:    K

In [55]: (
    ...:     arr.pint.quantify()
    ...:     .pint.to("degC")
    ...:     .pint.dequantify(format="~P")
    ...:     .to_netcdf("abc.nc")
    ...: )
    ...: with xr.open_dataset("abc.nc").load() as loaded:
    ...:     display(loaded)
    ...:     display(loaded.arr)
    ...: 
<xarray.Dataset>
Dimensions:  (x: 3)
Dimensions without coordinates: x
Data variables:
    arr      (x) float32 252.5 262.5 272.5
<xarray.DataArray 'arr' (x: 3)>
array([252.457  , 262.45724, 272.45685], dtype=float32)
Dimensions without coordinates: x
Attributes:
    units:    °C
```
I think this doesn't have to involve `pint-xarray` (we could assign values using `arr[:] = [3, 4, 5]` and would still load back the wrong values) so I'm going to forward this to the `xarray` issue tracker.

**Comment by keewis** [comment] 2021-07-24 12:42
closing, as this really is a issue in `xarray` (see pydata/xarray#5082)

**Closed by keewis** 2021-07-24 12:42 UTC
